### ISSUE TITLE
Notices

### ISSUE THREAD

**Issue by GaaraLi** [RogerTongTong/ruby_learning#2]
你好，我是Leo.Li 我今天看了一下你的代码，有几点小小的提示，希望能帮到你。
1，在我看代码的过程中，首先我并不知道这段代码是要来练习什么的，所以我并不是很清楚如何去评价这段代码的质量，因为解决同一个问题，不同的目的可能会出现不同的代码。建议：在文件开头以注释方式写出本段代码要完成的目的。当然，如果在本段学习过程中，有什么想法，也可以采用注释方式纪录在文件中，这样既方便你回过头来看，也方便以后有必要情况下，将你的这部分代码作为其他人学习过程中的参考。
2，我发现第三小节中你的输出变成了
```ruby
puts "current input: #{a}, result: #{b}"
```
而前两小节中是：
```ruby
print a," ",b," ",c," ",d, " ",e, "\n"
```
明显的第三小节更ruby。所以我希望你可以再发现有更好的方法的时候，能将之前代码中不是很满意的部分重构一下。
接下来是一个比较harsh的要求，如果希望挑战一下，可以尝试。
3，在完成学习计划中的题目的时候，或许可以去找找有没有更优雅的解法。
比如：
```ruby
original=[1,[2,[3,[4,[5]]]]]
a,(b,(c,(d,(e,f))))=original
print a," ",b," ",c," ",d, " ",e, "\n"

print original[0], " ", original[1][0], " ", original[1][1][0], " ", original[1][1][1][0], " ", original[1][1][1][1][0], "\n"
```
是否可以换成别的更加cool的解法，或许你会找到 __flatten__ 这个方法。再比如代码块这部分学习完成之后，或许你会想知道为什么会有Proc和lambda这两种不同的东西，区别在哪儿。也可以尝试把代码写得shorter and faster。
当然这些只是一些建议，比较mean，不过如果这样，或许能更快变成大牛！

这儿有几个比较权威的网站，如果有什么问题，或许会帮到你。
Ruby:
[Ruby Doc](http://www.ruby-doc.org/core-2.2.0/)
[Ruby China](https://ruby-china.org/)
Rails:
[Ruby on Rails Guide](http://guides.rubyonrails.org/)
[Ruby on Rails API](http://api.rubyonrails.org/)

**Comment by RogerTongTong** [comment]
Hi Leo,

很感谢你的建议。对于一个Ruby的初学者来说确实非常有帮助。

关于第一点建议 之前的练习输出确实没有加上合适的注视来让其他人知道是用来坐什么的。之后的练习我都会在其中加上合适的注视，不仅是给别人看，更是给自己复习来用

关于2、3点建议，我会在过完我的第一遍学习之后对所有的练习都做一次重构，相信到时候能像你说的写出更Ruby的代码来。也可以对其中的一些概念有更深刻的理解，能够多问出一些为什么。

**Comment by GaaraLi** [comment]
好的，有什么问题可以随时找我。
